version: '3'

services:
  db:
    image: bitnami/mongodb:latest
    ports:
      - '27017:27017'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGO_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes